import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from 'next/font/google'


const roboto = Montserrat({
  weight: '400',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "Nissan Silva",
  description: "Generated by Farid Mustafayev",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
          {children}
      </body>
    </html>
  );
}
