import type { Metadata } from "next";
import "./globals.css";
import { Baloo_2, Inter } from "next/font/google";

const baloo2 = Baloo_2({
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-baloo2",
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({
  weight: "400",
  variable: "--font-inter",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Animation",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${baloo2.variable} ${inter.variable}`}>
      <body className={`font-inter antialiased`}>
        {children} <div id="portal-root" />
      </body>
    </html>
  );
}
